<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <title>Code Challenge - Authentication</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
  <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
  <style>
    body {
      margin: 50px 0 0 0;
      padding: 0;
      width: 100%;
      font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
      text-align: center;
      color: #aaa;
      font-size: 18px;
    }

    h1, h2 {
      color: #719e40;
      letter-spacing: 0px;
      font-family: 'Lato', sans-serif;
      font-size: 30px;
      font-weight: 200;
      margin-bottom: 0;
    }

    h2 {
      font-size: 23px;
    }

    .loader {
      margin: auto;
      margin-top: 5vh;
      width: 3em;
      height: 3em;
      animation: loaderAnim 1.25s infinite;
      outline: 1px solid transparent;
    }
    .loader #largeBox {
      height: 3em;
      width: 3em;
      background-color: #ECECEC;
      outline: 1px solid transparent;
      position: fixed;
    }
    .loader #smallBox {
      height: 3em;
      width: 3em;
      background-color: #9e4040;
      position: fixed;
      z-index: 1;
      outline: 1px solid transparent;
      animation: smallBoxAnim 1.25s alternate infinite ease-in-out;
    }

    @keyframes smallBoxAnim {
      0% {
        transform: scale(0.2);
      }
      100% {
        transform: scale(0.75);
      }
    }
    @keyframes loaderAnim {
      0% {
        transform: rotate(0deg);
      }
      100% {
        transform: rotate(90deg);
      }
    }

  </style>
</head>
<body id="main">

  <h1>Code Challege - Authentication</h1>

  <div>
    You must now authenticate with Google Home.
  </div>

  <h2>
    Google Word: <?php echo $word ?>
  </h2>

  <div class="loader">
    <div id="largeBox"></div>
    <div id="smallBox"></div>
  </div>

  <script>

    $('document').ready(function(){
        setInterval(function(){

            $.ajax({
                url: 'http://192.168.33.12/developer-challenges/authentication/public/check-two-factor/<?php echo $twoFactorCode; ?>',
                beforeSend: function(xhr) {

                }, success: function(data){

                    console.log(data);

                  if(data.authenticated === true){

                      $( "#smallBox" ).animate({
                          backgroundColor: "#719e40",
                      }, 1000 );

                      setTimeout(function(){
                          //window.location.replace("/home");
                      }, 2000);

                  }

                }
            })


        }, 5000);
    });

  </script>

</body>
</html>
